### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Soochaehwa** [Soochaehwa/Lang-Miner#1]
- [x] 자동 주석 제거
- [x] 인덱스에 없는 모드 최초 추가시 한국어 있으면 한국어 같이 추출하고 없으면 빈 ko_kr.json 생성
- [ ] 패츌리 모드 언어 추출
- [x] 한국어 파일이씅면 생성안대야하는데 몬가 이상함...
